version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
     - aw-network
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
   image: grafana/grafana:latest
   ports:
    - 3000:3000
   networks:
    - aw-network

  